import openai
import os
import json
import time
import random

# =========================================================================
# === 1. YAPILANDIRMA AYARLARI ============================================
# =========================================================================

# OpenRouter API Anahtarınızı buraya girin
OPENROUTER_API_KEY = "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" 
OUTPUT_DIR = "ai_code_dataset"
TARGET_LANGUAGE = "python"
MAX_AI_BLOCKS = 2500  # HEDEF 5000 OLARAK GÜNCELLENDİ

# Modeller
AI_MODELS = [
    "openai/gpt-3.5-turbo",
    "mistralai/mixtral-8x7b-instruct",
    "meta-llama/llama-3-8b-instruct",
    "anthropic/claude-3-haiku", 
]
# Örnek prompt havuzu (Gerçekte 2500 adet olmalı!)
PROMPT_POOL = [
    # =====================================================================
    # 1. ALGORİTMİK GÖREVLER (Algorithmic Tasks) - 300 prompt
    # =====================================================================
    
    # Sıralama Algoritmaları (30)
    "Python'da yinelemeli (iterative) bir Hızlı Sıralama (Quicksort) algoritması yaz.",
    "Bubble Sort algoritmasını optimize edilmiş versiyonuyla birlikte yaz.",
    "Merge Sort algoritmasını in-place olmayan versiyonuyla uygula.",
    "Heap Sort algoritmasını min-heap kullanarak yaz.",
    "Insertion Sort'u binary search ile optimize et.",
    "Selection Sort algoritmasını küçükten büyüğe sıralama için yaz.",
    "Radix Sort algoritmasını tamsayılar için uygula.",
    "Counting Sort'u sınırlı aralıktaki sayılar için yaz.",
    "Shell Sort algoritmasını farklı gap dizileriyle uygula.",
    "Bucket Sort'u float sayılar için yaz.",
    "TimSort algoritmasının temel mantığını açıklayan basit bir versiyon yaz.",
    "Cocktail Shaker Sort (çift yönlü bubble sort) algoritmasını uygula.",
    "Comb Sort algoritmasını gap faktörü 1.3 ile yaz.",
    "Gnome Sort (Garden Gnome Sort) algoritmasını uygula.",
    "Pancake Sort algoritmasını flip operasyonlarıyla yaz.",
    "Bogo Sort (permütasyon sort) algoritmasını eğitim amaçlı yaz.",
    "Bitonic Sort algoritmasını paralel sıralama için yaz.",
    "Odd-Even Sort algoritmasını uygula.",
    "Cycle Sort algoritmasını minimum yazma işlemi için yaz.",
    "İki sıralı diziyi tek bir sıralı dizide birleştiren merge fonksiyonu yaz.",
    "Kısmen sıralı bir diziyi tamamen sıralamak için adaptive sort yaz.",
    "Stable ve unstable sort arasındaki farkı gösteren örnek kodlar yaz.",
    "Bir diziyi sadece 0, 1, 2 değerlerini içeriyorsa Dutch National Flag algoritmasıyla sırala.",
    "Wave Sort algoritmasını (zigzag pattern) uygula.",
    "3-way quicksort algoritmasını (Dutch partitioning) yaz.",
    "Introsort (intro sort) mantığını basitleştirilmiş olarak uygula.",
    "Patience Sort algoritmasını uygula.",
    "Strand Sort algoritmasını linked list için yaz.",
    "Bead Sort (gravity sort) algoritmasını pozitif tamsayılar için yaz.",
    "Smoothsort algoritmasının basitleştirilmiş versiyonunu yaz.",
    
    # Arama Algoritmaları (30)
    "Binary Search algoritmasını iterative ve recursive versiyonlarıyla yaz.",
    "Linear Search'ü sentinel tekniğiyle optimize et.",
    "Jump Search algoritmasını uygula.",
    "Interpolation Search'ü sıralı dizide yaz.",
    "Exponential Search algoritmasını büyük diziler için yaz.",
    "Fibonacci Search algoritmasını golden ratio ile uygula.",
    "Ternary Search'ü maksimum/minimum bulma için yaz.",
    "Sublist Search algoritmasını linked list için yaz.",
    "Ubiquitous Binary Search'ün farklı varyasyonlarını yaz.",
    "Rotated sorted array'de eleman arayan binary search varyasyonu yaz.",
    "2D matrix'te satır ve sütunlar sıralıyken eleman arayan algoritma yaz.",
    "Peak element (tepe eleman) bulan algoritma yaz.",
    "Bitap algoritmasını approximate string matching için yaz.",
    "Two Pointer tekniğiyle bir dizide çift toplam bulan fonksiyon yaz.",
    "Sliding Window tekniğiyle maksimum toplam alt dizi bulan fonksiyon yaz.",
    "Majority element (çoğunluk elemanı) bulan Boyer-Moore algoritmasını yaz.",
    "Missing number problemi için XOR tekniğini kullanan fonksiyon yaz.",
    "Sonsuz sıralı dizide eleman arayan algoritma yaz.",
    "First bad version bulan binary search varyasyonu yaz.",
    "Search in bitonic array (ilk artan sonra azalan) algoritması yaz.",
    "K-th smallest element'i bulan quickselect algoritmasını yaz.",
    "Median of two sorted arrays bulan optimal algoritma yaz.",
    "Local minimum bulan algoritma yaz.",
    "Square root hesaplayan binary search algoritması yaz.",
    "Fixed point (index == value) bulan algoritma yaz.",
    "Meta binary search (one-sided binary search) yaz.",
    "Recursive function to find nth Fibonacci using memoization yaz.",
    "Find the smallest missing positive integer in unsorted array.",
    "Search in row-wise and column-wise sorted matrix.",
    "Find kth largest element using heap.",
    
    # Graf Algoritmaları (40)
    "Python'da Dijkstra algoritmasının temel yapısını anlatan ve bir ağırlıklı grafiği temsil eden sınıfı kur.",
    "Breadth-First Search (BFS) algoritmasını graf için yaz.",
    "Depth-First Search (DFS) algoritmasını recursive ve iterative yaz.",
    "Bellman-Ford algoritmasını negatif ağırlıklı kenarlar için yaz.",
    "Floyd-Warshall algoritmasını all-pairs shortest path için yaz.",
    "Kruskal algoritmasını minimum spanning tree için yaz.",
    "Prim algoritmasını MST için priority queue ile yaz.",
    "Topological Sort algoritmasını DAG için yaz.",
    "Kosaraju algoritmasını strongly connected components için yaz.",
    "Tarjan algoritmasını SCC bulmak için yaz.",
    "A* pathfinding algoritmasını heuristic ile yaz.",
    "Johnson's algoritmasını sparse graph için yaz.",
    "Boruvka's algoritmasını MST için yaz.",
    "Edmonds-Karp algoritmasını max flow için yaz.",
    "Ford-Fulkerson algoritmasını network flow için yaz.",
    "Dinic's algoritmasını max flow için yaz.",
    "Push-relabel algoritmasını max flow için yaz.",
    "Hopcroft-Karp algoritmasını bipartite matching için yaz.",
    "Hungarian algoritmasını assignment problem için yaz.",
    "Travelling Salesman Problem için brute force çözüm yaz.",
    "TSP için dynamic programming çözümü yaz.",
    "Graph coloring için greedy algoritma yaz.",
    "Hamiltonian path bulan backtracking algoritması yaz.",
    "Eulerian path/circuit kontrol eden ve bulan algoritma yaz.",
    "Bridge (köprü) bulan Tarjan algoritması yaz.",
    "Articulation point (kesim noktası) bulan algoritma yaz.",
    "Cycle detection algoritmasını directed graph için yaz.",
    "Cycle detection algoritmasını undirected graph için yaz.",
    "Bipartite graph kontrol eden algoritma yaz.",
    "Graph'ın connected olup olmadığını kontrol eden fonksiyon yaz.",
    "Minimum cut bulan algoritma yaz.",
    "Chinese Postman Problem için temel çözüm yaz.",
    "Vertex cover problem için approximation algoritması yaz.",
    "Clique detection algoritması yaz.",
    "Independent set bulan algoritma yaz.",
    "Graph isomorphism kontrol eden basit algoritma yaz.",
    "Planarity testing için temel kontroller yaz.",
    "Centrality measures (degree, betweenness) hesaplayan fonksiyonlar yaz.",
    "PageRank algoritmasının basitleştirilmiş versiyonunu yaz.",
    "Community detection için Girvan-Newman algoritmasını yaz.",
    
    # Dinamik Programlama (40)
    "Fibonacci sayılarını memoization ile hesaplayan fonksiyon yaz.",
    "Fibonacci sayılarını tabulation (bottom-up) ile hesapla.",
    "Longest Common Subsequence (LCS) problemini DP ile çöz.",
    "Longest Increasing Subsequence (LIS) problemini çöz.",
    "0/1 Knapsack problemini dynamic programming ile yaz.",
    "Coin change problemini minimum coin count için çöz.",
    "Coin change problemini kaç farklı yolla yapılabileceğini bul.",
    "Edit Distance (Levenshtein) algoritmasını yaz.",
    "Matrix Chain Multiplication optimizasyonunu yaz.",
    "Longest Palindromic Subsequence bulan DP çözümü yaz.",
    "Longest Palindromic Substring bulan algoritma yaz.",
    "Rod cutting problem için maksimum kar hesapla.",
    "Egg dropping problem için minimum attempt sayısını bul.",
    "Partition problem (equal sum subsets) çözümü yaz.",
    "Subset sum problemini DP ile çöz.",
    "Longest Common Substring bulan algoritma yaz.",
    "Maximum sum increasing subsequence bul.",
    "Minimum cost path in a matrix hesapla.",
    "Count number of ways to reach nth stair yaz.",
    "Wildcard pattern matching algoritması yaz.",
    "Regular expression matching için DP çözümü yaz.",
    "Word break problem çözümü yaz.",
    "Palindrome partitioning için minimum cut sayısını bul.",
    "Maximum profit from stock buying/selling with cooldown.",
    "Interleaving string problem çözümü yaz.",
    "Burst balloons problem için maksimum coin hesapla.",
    "Dungeon game minimum initial health hesapla.",
    "Minimum ASCII delete sum for two strings.",
    "Maximum length of repeated subarray bul.",
    "Stone game winner prediction yaz.",
    "Scrambled string verification algoritması yaz.",
    "Distinct subsequences count yaz.",
    "Maximum rectangle in histogram yaz.",
    "Maximal rectangle in binary matrix bul.",
    "Trapping rain water problemini yaz.",
    "Decode ways for a digit string yaz.",
    "Unique paths in a grid with obstacles yaz.",
    "Minimum falling path sum hesapla.",
    "Cherry pickup maximum cherries yaz.",
    "Paint house with minimum cost yaz.",
    
    # Greedy Algoritmaları (30)
    "Activity selection problemini greedy yaklaşımla çöz.",
    "Fractional knapsack problemini greedy ile yaz.",
    "Huffman coding algoritmasını yaz.",
    "Job sequencing with deadlines problemini çöz.",
    "Minimum number of platforms required problemini yaz.",
    "Minimum number of coins for change (greedy approach) yaz.",
    "Egyptian fraction representation yaz.",
    "Minimize cash flow among friends problemini yaz.",
    "Connect n ropes with minimum cost yaz.",
    "K centers problem için greedy approximation yaz.",
    "Interval scheduling maximization yaz.",
    "Minimize maximum lateness scheduling yaz.",
    "Assign mice to holes problemini yaz.",
    "Minimum product subset of an array bul.",
    "Maximum trains for which stoppage can be provided yaz.",
    "Paper cut into minimum number of squares yaz.",
    "Minimum number of arrows to burst balloons yaz.",
    "Gas station circular tour problemini çöz.",
    "Policemen catch thieves problemini yaz.",
    "Minimum cost for tickets (travel planning) yaz.",
    "Maximize sum after k negations yaz.",
    "Minimum initial points to reach destination yaz.",
    "Minimum cost to connect all cities yaz.",
    "Chocolate distribution problem yaz.",
    "Minimum cost to cut a board into squares yaz.",
    "Fractional knapsack with multiple items yaz.",
    "Task scheduler with cooling interval yaz.",
    "Rearrange characters so no two adjacent are same yaz.",
    "Minimize maximum difference in heights yaz.",
    "Jump game to reach the end yaz.",
    
    # Backtracking (30)
    "N-Queens problemini backtracking ile çöz.",
    "Sudoku solver backtracking algoritması yaz.",
    "Rat in a maze problemini yaz.",
    "Knight's tour problemini yaz.",
    "Generate all permutations of a string yaz.",
    "Generate all combinations of parentheses yaz.",
    "Generate all subsets (power set) yaz.",
    "Word search in 2D board yaz.",
    "Combination sum problemini yaz.",
    "Generate all valid IP addresses yaz.",
    "M coloring problem yaz.",
    "Hamiltonian cycle problemini yaz.",
    "Solve cryptarithmetic puzzles yaz.",
    "Partition array into k subsets with equal sum yaz.",
    "Generate all palindrome partitions yaz.",
    "Letter combinations of phone number yaz.",
    "Restore IP addresses yaz.",
    "Word break II (all possible sentences) yaz.",
    "Additive number verification yaz.",
    "Beautiful arrangement count yaz.",
    "Generate all unique BSTs yaz.",
    "Tug of war (partition into two equal sum subsets) yaz.",
    "Expression add operators yaz.",
    "Remove invalid parentheses yaz.",
    "Optimal account balancing yaz.",
    "Matchsticks to square yaz.",
    "Shopping offers optimization yaz.",
    "Android unlock patterns count yaz.",
    "Strobogrammatic number generation yaz.",
    "Path with maximum gold collection yaz.",
    
    # Divide & Conquer (20)
    "Merge sort kullanarak inversion count yaz.",
    "Maximum subarray sum (Kadane's algorithm) yaz.",
    "Closest pair of points problemini yaz.",
    "Strassen's matrix multiplication yaz.",
    "Median of medians algoritmasını yaz.",
    "Karatsuba multiplication algoritmasını yaz.",
    "Binary search on answer tekniğini kullan.",
    "Count smaller elements on right side yaz.",
    "Skyline problem çözümü yaz.",
    "Power function (x^n) için O(log n) algoritma yaz.",
    "Find kth smallest in union of two sorted arrays yaz.",
    "Count inversions in an array yaz.",
    "Majority element II (elements appearing > n/3 times) yaz.",
    "Maximum gap in sorted array yaz.",
    "Reverse pairs count yaz.",
    "Different ways to add parentheses yaz.",
    "Beautiful array generation yaz.",
    "Count of range sum in an array yaz.",
    "Longest substring with at most k distinct characters yaz.",
    "Median in a stream using heaps yaz.",
    
    # Bit Manipulation (30)
    "Bir sayının binary gösterimindeki 1'lerin sayısını bul.",
    "İki sayıyı aritmetik operatörler kullanmadan topla.",
    "Bir sayının power of 2 olup olmadığını kontrol et.",
    "XOR kullanarak swap işlemi yap.",
    "Bir sayının i'nci bitini set/clear/toggle eden fonksiyonlar yaz.",
    "İki sayının hamming distance'ını hesapla.",
    "Bir dizideki tek bir tekrarsız sayıyı XOR ile bul.",
    "Missing number'ı XOR ile bul.",
    "Reverse bits of a 32-bit integer yaz.",
    "Count trailing zeros in binary representation yaz.",
    "Find position of rightmost set bit yaz.",
    "Check if a number is sparse (no consecutive 1s) yaz.",
    "Next power of 2 bul.",
    "Swap all odd and even bits yaz.",
    "Find two non-repeating elements in array yaz.",
    "Binary representation of a decimal fraction yaz.",
    "Count total set bits in all numbers from 1 to n yaz.",
    "Find XOR of all subsets yaz.",
    "Check if binary representation is palindrome yaz.",
    "Rotate bits of a number yaz.",
    "Find element that appears once while others appear thrice yaz.",
    "Maximum XOR of two numbers in array yaz.",
    "Count number of bits to flip to convert A to B yaz.",
    "Find the only number occurring odd times yaz.",
    "Generate all possible subsets using bits yaz.",
    "Check if a number is bleak yaz.",
    "Find the two's complement yaz.",
    "Flip bits to make alternate pattern yaz.",
    "Find maximum AND value pair yaz.",
    "Minimum XOR value pair yaz.",
    
    # Matematiksel Algoritmalar (30)
    "Girilen bir sayının asal çarpanlarını (Prime Factors) bulan bir kod bloğu oluştur.",
    "GCD (Greatest Common Divisor) hesaplayan Euclidean algoritması yaz.",
    "LCM (Least Common Multiple) hesaplayan fonksiyon yaz.",
    "Sieve of Eratosthenes ile belirli bir sayıya kadar asal sayıları bul.",
    "Modular exponentiation (fast power) algoritması yaz.",
    "Fermat's little theorem kullanarak modular inverse bul.",
    "Extended Euclidean algorithm yaz.",
    "Prime factorization using Pollard's rho algoritması yaz.",
    "Check if a number is perfect number yaz.",
    "Generate Catalan numbers yaz.",
    "Compute nCr (binomial coefficient) yaz.",
    "Pascal's triangle generator yaz.",
    "Find all divisors of a number efficiently yaz.",
    "Sum of divisors of a number yaz.",
    "Euler's totient function hesapla.",
    "Chinese remainder theorem uygula.",
    "Modular multiplicative inverse bul.",
    "Count number of trailing zeros in factorial yaz.",
    "Check if a number is Armstrong number yaz.",
    "Generate prime numbers using trial division yaz.",
    "Baby-step giant-step algorithm for discrete log yaz.",
    "Miller-Rabin primality test yaz.",
    "Lucas-Lehmer primality test for Mersenne primes yaz.",
    "Legendre symbol calculation yaz.",
    "Pollard's p-1 factorization yaz.",
    "Quadratic sieve basics yaz.",
    "Fast Fourier Transform basics yaz.",
    "Number theoretic transform yaz.",
    "Matrix exponentiation yaz.",
    "Josephus problem solution yaz.",
    
    # String Algoritmaları (30)
    "KMP (Knuth-Morris-Pratt) pattern matching yaz.",
    "Rabin-Karp algorithm for pattern searching yaz.",
    "Z-algorithm for pattern matching yaz.",
    "Manacher's algorithm for longest palindromic substring yaz.",
    "Aho-Corasick algorithm for multiple pattern search yaz.",
    "Suffix array construction yaz.",
    "Longest common prefix array construction yaz.",
    "Burrows-Wheeler transform yaz.",
    "Run-length encoding implementation yaz.",
    "Implement Trie data structure yaz.",
    "Suffix tree construction basics yaz.",
    "Anagram grouping yaz.",
    "Find all anagrams in a string yaz.",
    "Minimum window substring yaz.",
    "String compression algorithm yaz.",
    "Reverse words in a string yaz.",
    "Longest substring without repeating characters yaz.",
    "Check if string is rotation of another yaz.",
    "Count and say sequence generator yaz.",
    "Integer to roman numeral converter yaz.",
    "Roman numeral to integer converter yaz.",
    "Zigzag conversion yaz.",
    "Group shifted strings yaz.",
    "Compare version numbers yaz.",
    "Valid number checker yaz.",
    "Multiply strings as numbers yaz.",
    "Add binary strings yaz.",
    "Simplify Unix path yaz.",
    "Text justification yaz.",
    "Encode and decode strings yaz.",
    
    # =====================================================================
    # 2. VERİ YAPILARI (Data Structures) - 250 prompt
    # =====================================================================
    
    # Linked List (40)
    "Singly linked list için Node ve LinkedList sınıfı oluştur.",
    "Linked list'e başa eleman ekleme fonksiyonu yaz.",
    "Linked list'e sona eleman ekleme fonksiyonu yaz.",
    "Linked list'ten eleman silme fonksiyonu yaz.",
    "Linked list'i reverse eden fonksiyon yaz.",
    "Linked list'te cycle detection (Floyd's algorithm) yaz.",
    "İki linked list'i merge eden fonksiyon yaz.",
    "Linked list'in ortasını bulan fonksiyon yaz.",
    "Doubly linked list implementation yaz.",
    "Circular linked list implementation yaz.",
    "Linked list'ten duplicates removal yaz.",
    "Nth node from end of linked list bul.",
    "Palindrome linked list checker yaz.",
    "Partition linked list around a value yaz.",
    "Add two numbers represented as linked lists yaz.",
    "Flatten a multilevel doubly linked list yaz.",
    "Copy list with random pointer yaz.",
    "Intersection point of two linked lists bul.",
    "Remove nth node from end yaz.",
    "Swap nodes in pairs yaz.",
    "Reverse nodes in k-group yaz.",
    "Rotate linked list by k positions yaz.",
    "Merge k sorted linked lists yaz.",
    "Sort linked list using merge sort yaz.",
    "Reorder linked list (L0→Ln→L1→Ln-1...) yaz.",
    "Linked list cycle II (find start of cycle) yaz.",
    "Remove zero sum consecutive nodes yaz.",
    "Plus one to number in linked list yaz.",
    "Convert binary number in linked list to integer yaz.",
    "Delete middle node of linked list yaz.",
    "Reverse alternate k nodes yaz.",
    "Pairwise swap nodes yaz.",
    "Clone linked list with next and random pointers yaz.",
    "Segregate even and odd nodes yaz.",
    "Delete N nodes after M nodes yaz.",
    "Find triplet with given sum in linked list yaz.",
    "QuickSort on doubly linked list yaz.",
    "Insert in sorted circular linked list yaz.",
    "Split circular linked list into two halves yaz.",
    "Check if linked list is sorted yaz.",
    
    # Stack (30)
    "Python listesi kullanarak stack implementation yaz.",
    "Stack kullanarak parantez dengeleme kontrol et.",
    "İki stack kullanarak queue implementation yaz.",
    "Min stack (constant time getMin) yaz.",
    "Stack kullanarak infix to postfix conversion yaz.",
    "Postfix expression evaluation yaz.",
    "Next greater element using stack yaz.",
    "Stock span problem using stack yaz.",
    "Largest rectangle in histogram using stack yaz.",
    "Celebrity problem using stack yaz.",
    "Sort a stack using recursion yaz.",
    "Reverse a stack using recursion yaz.",
    "Implement k stacks in an array yaz.",
    "Design a stack with increment operation yaz.",
    "Simplify directory path using stack yaz.",
    "Decode string using stack yaz.",
    "Remove duplicate letters using stack yaz.",
    "Validate stack sequences yaz.",
    "Exclusive time of functions using stack yaz.",
    "Score of parentheses using stack yaz.",
    "Remove outermost parentheses using stack yaz.",
    "Minimum remove to make valid parentheses yaz.",
    "Maximum frequency stack yaz.",
    "Online stock span yaz.",
    "Daily temperatures using stack yaz.",
    "Sum of subarray minimums using stack yaz.",
    "Check if word is valid after substitutions yaz.",
    "Asteroid collision using stack yaz.",
    "132 pattern using stack yaz.",
    "Car fleet problem using stack yaz.",
    
    # Queue (25)
    "Python'da bir kuyruk (Queue) veri yapısını temsil eden, `enqueue` ve `dequeue` metodlarına sahip bir sınıf oluştur.",
    "Circular queue implementation yaz.",
    "Priority queue using heap yaz.",
    "Deque (double-ended queue) implementation yaz.",
    "Queue using two stacks yaz.",
    "LRU Cache implementation using queue and hash yaz.",
    "Generate binary numbers from 1 to n using queue yaz.",
    "First non-repeating character in stream using queue yaz.",
    "Sliding window maximum using deque yaz.",
    "Rotting oranges BFS using queue yaz.",
    "Design circular deque yaz.",
    "Reveal cards in increasing order using queue yaz.",
    "Recent counter using queue yaz.",
    "Time needed to buy tickets using queue yaz.",
    "Moving average from data stream using queue yaz.",
    "Number of recent calls using queue yaz.",
    "Design front middle back queue yaz.",
    "Dota2 Senate problem using queue yaz.",
    "Jump game VI using deque yaz.",
    "Shortest subarray with sum at least k using deque yaz.",
    "Max value of equation using deque yaz.",
    "Constrained subsequence sum using deque yaz.",
    "Continuous subarrays using deque yaz.",
    "Find the winner of circular game using queue yaz.",
    "Task scheduler using queue yaz.",
    
    # Tree (Binary Tree, BST) (40)
    "İkili bir ağacın (Binary Tree) derinliğini hesaplayan bir sınıf metodu geliştir.",
    "Binary tree inorder traversal (iterative ve recursive) yaz.",
    "Binary tree preorder traversal yaz.",
    "Binary tree postorder traversal yaz.",
    "Level order traversal using queue yaz.",
    "Zigzag level order traversal yaz.",
    "Binary tree right side view yaz.",
    "Symmetric tree checker yaz.",
    "Invert binary tree yaz.",
    "Diameter of binary tree yaz.",
    "Maximum depth of binary tree yaz.",
    "Minimum depth of binary tree yaz.",
    "Path sum checker yaz.",
    "Path sum II (all paths) yaz.",
    "Binary tree paths yaz.",
    "Sum of left leaves yaz.",
    "Lowest common ancestor in BST yaz.",
    "Lowest common ancestor in binary tree yaz.",
    "Validate binary search tree yaz.",
    "Convert sorted array to BST yaz.",
    "Convert sorted list to BST yaz.",
    "BST iterator yaz.",
    "Kth smallest element in BST yaz.",
    "Delete node in BST yaz.",
    "Insert into BST yaz.",
    "Search in BST yaz.",
    "Recover BST yaz.",
    "Unique BST count yaz.",
    "Unique BST generation yaz.",
    "Construct binary tree from preorder and inorder yaz.",
    "Construct binary tree from inorder and postorder yaz.",
    "Serialize and deserialize binary tree yaz.",
    "Flatten binary tree to linked list yaz.",
    "Populate next right pointers yaz.",
    "Binary tree maximum path sum yaz.",
    "Sum root to leaf numbers yaz.",
    "Count complete tree nodes yaz.",
    "Find leaves of binary tree yaz.",
    "Binary tree vertical order traversal yaz.",
    "Morris traversal implementation yaz.",
    
    # Heap / Priority Queue (25)
    "Min heap implementation from scratch yaz.",
    "Max heap implementation yaz.",
    "Heapify process yaz.",
    "Heap sort implementation yaz.",
    "Kth largest element using heap yaz.",
    "Top k frequent elements using heap yaz.",
    "Merge k sorted arrays using heap yaz.",
    "Find median from data stream using heaps yaz.",
    "Reorganize string using heap yaz.",
    "K closest points to origin using heap yaz.",
    "Kth smallest element in sorted matrix using heap yaz.",
    "Ugly number II using heap yaz.",
    "Find k pairs with smallest sums using heap yaz.",
    "Distant barcodes using heap yaz.",
    "Task scheduler using heap yaz.",
    "Minimum cost to hire k workers using heap yaz.",
    "IPO problem using heaps yaz.",
    "Cheapest flights within k stops using heap yaz.",
    "Network delay time using Dijkstra with heap yaz.",
    "Last stone weight using max heap yaz.",
    "K weakest rows using heap yaz.",
    "Furthest building you can reach using heap yaz.",
    "Single threaded CPU using heap yaz.",
    "Find subsequence of length k with largest sum using heap yaz.",
    "Seat reservation manager using heap yaz.",
    
    # Hash Table / Dictionary (30)
    "Hash table implementation with chaining yaz.",
    "Hash table with open addressing yaz.",
    "Two sum problem using hash map yaz.",
    "Group anagrams using hash map yaz.",
    "Longest consecutive sequence using hash set yaz.",
    "Subarray sum equals k using hash map yaz.",
    "Longest substring without repeating chars using hash map yaz.",
    "Find duplicate in array using hash set yaz.",
    "First unique character using hash map yaz.",
    "Isomorphic strings checker using hash map yaz.",
    "Word pattern checker using hash map yaz.",
    "Contains duplicate II using hash map yaz.",
    "Happy number using hash set yaz.",
    "Valid Sudoku using hash sets yaz.",
    "Group shifted strings using hash map yaz.",
    "Logger rate limiter using hash map yaz.",
    "Design underground system using hash maps yaz.",
    "Time based key-value store using hash map yaz.",
    "LFU cache implementation yaz.",
    "Design Twitter using hash maps yaz.",
    "Insert delete getRandom O(1) using hash map and list yaz.",
    "All O(1) data structure yaz.",
    "Maximum frequency stack using hash map yaz.",
    "Design hashset from scratch yaz.",
    "Design hashmap from scratch yaz.",
    "Encode and decode TinyURL using hash map yaz.",
    "Ransom note checker using hash map yaz.",
    "Find common characters using hash map yaz.",
    "Intersection of arrays using hash set yaz.",
    "Custom sort string using hash map yaz.",
    
    # Trie (15)
    "Trie (Prefix Tree) implementation yaz.",
    "Insert word into trie yaz.",
    "Search word in trie yaz.",
    "Search prefix in trie yaz.",
    "Delete word from trie yaz.",
    "Word search II using trie yaz.",
    "Replace words using trie yaz.",
    "Map sum pairs using trie yaz.",
    "Design add and search words data structure yaz.",
    "Longest word in dictionary using trie yaz.",
    "Implement magic dictionary using trie yaz.",
    "Stream of characters using trie yaz.",
    "Concatenated words using trie yaz.",
    "Prefix and suffix search using trie yaz.",
    "Word filter using trie yaz.",
    
    # Graph (15)
    "Graph representation using adjacency list yaz.",
    "Graph representation using adjacency matrix yaz.",
    "Add edge to graph yaz.",
    "Remove edge from graph yaz.",
    "Check if path exists using DFS yaz.",
    "Check if path exists using BFS yaz.",
    "Count connected components yaz.",
    "Detect cycle in undirected graph yaz.",
    "Detect cycle in directed graph yaz.",
    "Clone graph yaz.",
    "Course schedule using topological sort yaz.",
    "Course schedule II yaz.",
    "Find eventual safe states yaz.",
    "All paths from source to target yaz.",
    "Minimum number of vertices to reach all nodes yaz.",
    
    # Disjoint Set / Union Find (15)
    "Union Find implementation yaz.",
    "Union by rank optimization yaz.",
    "Path compression optimization yaz.",
    "Number of connected components using union find yaz.",
    "Graph valid tree using union find yaz.",
    "Redundant connection using union find yaz.",
    "Accounts merge using union find yaz.",
    "Number of provinces using union find yaz.",
    "Smallest string with swaps using union find yaz.",
    "Satisfiability of equality equations using union find yaz.",
    "Regions cut by slashes using union find yaz.",
    "Remove max number of edges to keep graph traversable yaz.",
    "Checking existence of edge length limited paths yaz.",
    "Minimize malware spread using union find yaz.",
    "Swim in rising water using union find yaz.",
    
    # Segment Tree / Fenwick Tree (10)
    "Segment tree implementation for range sum query yaz.",
    "Segment tree for range minimum query yaz.",
    "Lazy propagation in segment tree yaz.",
    "Fenwick tree (Binary Indexed Tree) implementation yaz.",
    "Range sum query using Fenwick tree yaz.",
    "Count of smaller numbers after self using Fenwick tree yaz.",
    "Range sum query 2D using Fenwick tree yaz.",
    "Count inversions using Fenwick tree yaz.",
    "Reverse pairs using Fenwick tree yaz.",
    "Count of range sum using segment tree yaz.",
    
    # =====================================================================
    # 3. FONKSİYONEL & API GÖREVLERİ (Functional & API Tasks) - 200 prompt
    # =====================================================================
    
    # HTTP Requests & API Calls (40)
    "requests kütüphanesini kullanarak belirli bir URL'ye POST isteği gönderen ve yanıtın durum kodunu döndüren bir fonksiyon oluştur.",
    "GET request yapan ve JSON response döndüren fonksiyon yaz.",
    "API'ye authentication header ile istek gönderen fonksiyon yaz.",
    "Timeout parametreli HTTP request yapan fonksiyon yaz.",
    "Retry mekanizması olan API request fonksiyonu yaz.",
    "Multiple endpoints'e parallel request gönderen fonksiyon yaz.",
    "Rate limiting ile API request yapan fonksiyon yaz.",
    "API response'u cache'leyen decorator yaz.",
    "REST API PUT request ile veri güncelleyen fonksiyon yaz.",
    "DELETE request ile kaynak silen fonksiyon yaz.",
    "Query parameters ile GET request yapan fonksiyon yaz.",
    "Form data POST request yapan fonksiyon yaz.",
    "Multipart/form-data file upload yapan fonksiyon yaz.",
    "PATCH request ile partial update yapan fonksiyon yaz.",
    "Bearer token authentication kullanarak request yapan fonksiyon yaz.",
    "Basic authentication ile request yapan fonksiyon yaz.",
    "OAuth2 token refresh yapan fonksiyon yaz.",
    "API response pagination handle eden fonksiyon yaz.",
    "GraphQL query gönderen fonksiyon yaz.",
    "WebSocket connection açan fonksiyon yaz.",
    "Server-sent events dinleyen fonksiyon yaz.",
    "HTTP headers parse eden fonksiyon yaz.",
    "Cookies yöneten request fonksiyonu yaz.",
    "Session management yapan API client yaz.",
    "API response validation yapan fonksiyon yaz.",
    "Error handling ile comprehensive request wrapper yaz.",
    "Async HTTP request yapan aiohttp kullanımlı fonksiyon yaz.",
    "Concurrent API calls yapan ThreadPoolExecutor örneği yaz.",
    "API response mock eden test fonksiyonu yaz.",
    "Request interceptor pattern uygula.",
    "Response cache middleware yaz.",
    "API client class with connection pooling yaz.",
    "Streaming API response handle eden fonksiyon yaz.",
    "File download progress bar ile fonksiyon yaz.",
    "Chunked file upload yapan fonksiyon yaz.",
    "API rate limit header checker yaz.",
    "Custom user agent ile request yapan fonksiyon yaz.",
    "Proxy kullanarak request yapan fonksiyon yaz.",
    "SSL certificate verification yapılandırmalı request yaz.",
    "API versioning handle eden client yaz.",
    
    # Flask/FastAPI Web Development (40)
    "Flask kullanarak, bir URL parametresi (/user/<name>) kabul eden basit bir rotayı (route) tanımla.",
    "Flask ile JSON response döndüren endpoint yaz.",
    "Flask ile POST data alan endpoint yaz.",
    "Flask middleware örneği yaz.",
    "Flask ile error handler tanımla.",
    "Flask blueprint kullanarak modular yapı oluştur.",
    "Flask ile authentication decorator yaz.",
    "Flask ile rate limiting decorator yaz.",
    "Flask ile CORS configuration yaz.",
    "Flask ile file upload endpoint yaz.",
    "Flask ile pagination yapan endpoint yaz.",
    "Flask ile query parameters alan endpoint yaz.",
    "Flask ile request validation yapan fonksiyon yaz.",
    "Flask ile JWT authentication yaz.",
    "Flask ile session management yaz.",
    "Flask ile cookie set eden endpoint yaz.",
    "FastAPI ile GET endpoint yaz.",
    "FastAPI ile POST endpoint with Pydantic model yaz.",
    "FastAPI ile path parameters alan endpoint yaz.",
    "FastAPI ile query parameters validation yaz.",
    "FastAPI ile response model tanımla.",
    "FastAPI ile dependency injection örneği yaz.",
    "FastAPI ile background tasks yaz.",
    "FastAPI ile file upload endpoint yaz.",
    "FastAPI ile WebSocket endpoint yaz.",
    "FastAPI ile OAuth2 password flow yaz.",
    "FastAPI ile API key authentication yaz.",
    "FastAPI ile CORS middleware yaz.",
    "FastAPI ile custom exception handler yaz.",
    "FastAPI ile request/response middleware yaz.",
    "FastAPI ile startup/shutdown events yaz.",
    "FastAPI ile async endpoint yaz.",
    "FastAPI ile streaming response yaz.",
    "Flask-RESTful ile resource class yaz.",
    "Flask-SocketIO ile real-time endpoint yaz.",
    "Flask ile template rendering yapan endpoint yaz.",
    "Flask ile redirect yapan endpoint yaz.",
    "Flask ile JSON Web Token expire kontrolü yaz.",
    "Flask ile API documentation swagger entegrasyonu yaz.",
    "FastAPI ile automatic OpenAPI documentation özelleştir.",
    
    # File Operations & Path Handling (30)
    "Dosya yolunu parametre olarak alan ve dosyanın uzantısını (örn: .txt) döndüren güvenli bir fonksiyon yaz.",
    "CSV dosyasını okuyan ve tüm verileri satır satır bir liste içinde döndüren bir fonksiyon oluştur.",
    "Bir metin dosyasını satır satır okuyan ve her satırı büyük harfe çevirerek yeni bir dosyaya yazan bir işlev yaz.",
    "Bir metin dosyasının son N satırını (N parametre olarak verilmeli) okuyup liste olarak döndüren bir işlev oluştur.",
    "Python'da bir dosyayı açıp okurken kaynak sızıntısını önlemek için with ifadesini kullanan bir örnek yaz.",
    "Bir metin dosyasını okurken oluşabilecek FileNotFoundError istisnasını yakala ve kullanıcı dostu bir mesaj yazdır.",
    "JSON dosyası okuyup Python dictionary'ye çeviren fonksiyon yaz.",
    "Python dictionary'yi JSON dosyasına yazan fonksiyon yaz.",
    "YAML dosyası parse eden fonksiyon yaz.",
    "INI configuration dosyası okuyan fonksiyon yaz.",
    "XML dosyası parse eden fonksiyon yaz.",
    "Binary dosya okuma/yazma fonksiyonu yaz.",
    "Dosya var mı kontrol eden safe reader yaz.",
    "Directory içindeki tüm dosyaları listeleyen fonksiyon yaz.",
    "Recursive olarak subdirectory'lerdeki dosyaları bulan fonksiyon yaz.",
    "Dosya boyutunu human-readable format'ta döndüren fonksiyon yaz.",
    "Dosya creation/modification time'ı alan fonksiyon yaz.",
    "Temporary file oluşturan context manager yaz.",
    "Dosyaları pattern'e göre filtreleyen fonksiyon yaz.",
    "Dosya izinlerini kontrol eden fonksiyon yaz.",
    "Symlink oluşturan ve kontrol eden fonksiyon yaz.",
    "Directory oluşturan (recursive) fonksiyon yaz.",
    "Dosya taşıma/kopyalama fonksiyonu yaz.",
    "Archive (zip/tar) oluşturan fonksiyon yaz.",
    "Archive extract eden fonksiyon yaz.",
    "File watcher (changes monitor) implementation yaz.",
    "Dosya hash (MD5/SHA256) hesaplayan fonksiyon yaz.",
    "Large file'ı chunk'lar halinde okuyan generator yaz.",
    "Memory-efficient file comparison fonksiyonu yaz.",
    "Path normalization ve validation yapan fonksiyon yaz.",
    
    # Data Parsing & Serialization (25)
    "JSON string'i parse edip pretty print yapan fonksiyon yaz.",
    "Nested JSON'dan belirli key'i extract eden fonksiyon yaz.",
    "XML'i dictionary'ye convert eden fonksiyon yaz.",
    "Dictionary'yi XML'e convert eden fonksiyon yaz.",
    "CSV'yi pandas DataFrame'e çeviren fonksiyon yaz.",
    "DataFrame'i CSV'ye export eden fonksiyon yaz.",
    "Excel dosyası okuyan fonksiyon yaz.",
    "Multiple sheets olan Excel'i parse eden fonksiyon yaz.",
    "DataFrame'i Excel'e yazan fonksiyon yaz.",
    "Pickle ile object serialization yapan fonksiyon yaz.",
    "Pickle'dan object deserialize eden fonksiyon yaz.",
    "MessagePack serialization/deserialization yaz.",
    "Protocol Buffers basic usage örneği yaz.",
    "Base64 encoding/decoding fonksiyonu yaz.",
    "URL encoding/decoding fonksiyonu yaz.",
    "HTML entities encode/decode yapan fonksiyon yaz.",
    "Unicode normalization yapan fonksiyon yaz.",
    "Custom object'i JSON serializable yapan encoder yaz.",
    "Datetime object'leri JSON'a serialize eden fonksiyon yaz.",
    "Enum'ları serialize eden custom encoder yaz.",
    "Nested dataclass'ları serialize/deserialize eden fonksiyon yaz.",
    "TOML dosyası parse eden fonksiyon yaz.",
    "Environment variables'ı parse eden fonksiyon yaz.",
    ".env dosyası okuyan fonksiyon yaz.",
    "Configuration merger (multiple configs) fonksionu yaz.",
    
    # Logging & Monitoring (20)
    "Logging modülünü kullanarak, kritik hataları bir dosyaya (app.log) kaydeden basit bir yapılandırma örneği oluştur.",
    "Rotating file handler ile log yaz.",
    "Multiple handlers (file + console) ile logger yaz.",
    "Custom log formatter yaz.",
    "Log level filtering yapan handler yaz.",
    "JSON formatted logs oluşturan formatter yaz.",
    "Structured logging implementation yaz.",
    "Exception logging decorator yaz.",
    "Function execution time logger decorator yaz.",
    "Request/response logging middleware yaz.",
    "Performance monitoring decorator yaz.",
    "Memory usage tracking decorator yaz.",
    "Custom metrics collector class yaz.",
    "Health check endpoint implementation yaz.",
    "Status monitoring dashboard data generator yaz.",
    "Error rate calculator yaz.",
    "Alert trigger condition checker yaz.",
    "Log aggregation fonksiyonu yaz.",
    "Log analysis ve statistics extractor yaz.",
    "Audit trail logger yaz.",
    
    # Validation & Data Processing (25)
    "Kullanıcının girdiği bir şifrenin en az 8 karakter, bir büyük harf ve bir rakam içerip içermediğini kontrol eden bir doğrulama fonksiyonu yaz.",
    "Email validation regex ile fonksiyon yaz.",
    "Phone number validation fonksiyonu yaz.",
    "URL validation fonksiyonu yaz.",
    "Credit card number Luhn algorithm ile validate eden fonksiyon yaz.",
    "IP address validation (IPv4/IPv6) fonksiyonu yaz.",
    "MAC address validation fonksiyonu yaz.",
    "UUID validation fonksiyonu yaz.",
    "Date format validation fonksiyonu yaz.",
    "JSON schema validation örneği yaz.",
    "Pydantic model ile data validation yaz.",
    "Custom validator decorator yaz.",
    "Input sanitization fonksiyonu yaz.",
    "SQL injection prevention validator yaz.",
    "XSS prevention fonksiyonu yaz.",
    "CSRF token generator ve validator yaz.",
    "Rate limit validator yaz.",
    "Age verification fonksiyonu yaz.",
    "Postal code validation fonksiyonu yaz.",
    "IBAN validation fonksiyonu yaz.",
    "Password strength checker yaz.",
    "Username availability checker yaz.",
    "File type validation fonksiyonu yaz.",
    "File size limit validator yaz.",
    "Image dimensions validator yaz.",
    
    # Utility Functions (20)
    "Bir fonksiyona gelen tüm argümanları **kwargs kullanarak alan ve bunları bir JSON string'i olarak döndüren bir fonksiyon yaz.",
    "Verilen bir tarihin (string formatında) bir yıl, ay ve gün tuple'ı olarak döndüren bir tarih ayrıştırma fonksiyonu yaz.",
    "Retry decorator with exponential backoff yaz.",
    "Memoization decorator yaz.",
    "Cache decorator with TTL yaz.",
    "Singleton pattern decorator yaz.",
    "Timing decorator yaz.",
    "Deprecation warning decorator yaz.",
    "Type checking decorator yaz.",
    "Context manager for timer yaz.",
    "Context manager for database transaction yaz.",
    "Context manager for file locking yaz.",
    "Debounce decorator yaz.",
    "Throttle decorator yaz.",
    "Circuit breaker pattern implementation yaz.",
    "Lazy property decorator yaz.",
    "Class property decorator yaz.",
    "Method chaining implementation yaz.",
    "Fluent interface example yaz.",
    "Builder pattern implementation yaz."
    """"Aşağıdaki Python kodundaki mantık hatasını bul, düzelt ve düzeltmenin nedenini detaylı bir yorumla açıkla: 
    def calculate_average(numbers):
        if not numbers:
            return 0
        total = sum(numbers)
        return total / len(numbers) if len(numbers) > 0 else 0 
    """,
    "Aşağıdaki kod parçasının potansiyel olarak fırlatabileceği KeyError hatasını, sözlüğe güvenli erişim sağlayarak (get metodu) düzelt:",
    "Bu kodu daha okunabilir hale getirmek için **refactor** et: İç içe 3 if-else bloğu olan bir fonksiyon yaz.",
    "Bir döngü içinde gereksiz yere tanımlanmış değişkeni döngü dışına alarak bu kodu refactor et.",
    "Aşağıdaki kodu **list comprehension** kullanarak tek satırda yeniden yaz:",
    "Aşağıdaki fonksiyonun **docstring**'ini Google/Numpy stiline uygun olarak tamamlama ve **type hints** ekle.",
    "Aşağıdaki kodu, **'EAFP'** (izin istemektense af dile) prensibi yerine **'LBYL'** (atlamadan önce bak) prensibini kullanarak yeniden yaz.",
    "Aşağıdaki kodda kullanılmayan değişkeni kaldırarak kodu temizle.",
    "Aşağıdaki fonksiyonu, **Guard Clause** (Erken çıkış) kullanarak refactor et.",
    "Bir fonksiyonun tüm parametrelerini **keyword-only** olacak şekilde yeniden yaz.",
    "Aşağıdaki koddaki **yakalanmamış istisna (unhandled exception)** nerede ve nasıl düzeltilmelidir?",
    "Yanlış girintilenmiş (indentation) aşağıdaki kod bloğunu düzelt.",
    "Aşağıdaki koddaki **global değişken kullanımını** argüman ve geri dönüş değerleri kullanarak düzelt.",
    "Aşağıdaki kodun **unit test'ini** yaz (en az 3 farklı senaryo içersin).",
    "Bir fonksiyonun **assertion** kullanarak girdi doğrulamasını nasıl yapacağını gösteren bir örnek yaz.",
    "Aşağıdaki kodu **ternary operator** kullanarak tek satırda yaz.",
    "Kod tekrarını önlemek için (DRY prensibi) iki benzer fonksiyonu tek bir fonksiyon altında birleştir.",
    "Aşağıdaki kodu **with** ifadesi kullanarak kaynak yönetimini iyileştirerek yeniden yaz.",
    "Aşağıdaki kod bloğuna **minimum 10 satır detaylı açıklayıcı yorum** ekle.",
    "Aşağıdaki sınıfın **kapsamlı** bir `__repr__` metodu yaz.",

    # Minimalist ve Kısa Kod (20)
    "İki listeyi tek bir listeye birleştiren tek satırlık bir kod yaz.",
    "Bir listedeki sadece pozitif sayıların toplamını bulan tek satırlık bir kod yaz.",
    "Bir sözlükteki tüm değerlerin karesini alan tek satırlık bir dictionary comprehension yaz.",
    "Bir dizeyi tersten yazdıran en kısa kodu yaz.",
    "İki değişkenin değerini geçici değişken kullanmadan değiştiren (swap) en kısa Python kodu yaz.",
    "Bir liste elemanına koşullu olarak işlem uygulayan tek satırlık list comprehension yaz.",
    "Bir listenin rastgele bir elemanını döndüren tek satırlık bir ifade yaz.",
    "Bir dizedeki tüm sesli harfleri kaldıran tek satırlık bir kod yaz.",
    "İki liste arasındaki farkı (set difference) bulan tek satırlık bir kod yaz.",
    "İki string'in birbirinin anagramı olup olmadığını kontrol eden kısa bir fonksiyon yaz.",
    "Bir dizedeki harflerin frekansını hesaplayan tek satırlık bir Counter/Dict kullanımı yaz.",
    "Bir listeyi hem indeks hem de değerle döngüye alan en kısa kodu yaz.",
    "Bir sayının çift olup olmadığını kontrol eden bir lambda fonksiyonu yaz.",
    "Bir listedeki boş (None) değerleri kaldıran tek satırlık bir kod yaz.",
    "Bir listeyi ters sırada numaralandıran (enumerate) bir generator yaz.",
    "Bir listedeki en büyük ve en küçük sayıyı aynı anda bulan tek satırlık kodu yaz.",
    "Bir listeyi **flatten** (düzleştirme) yapan tek satırlık bir list comprehension yaz.",
    "Python'da bir tarih objesinin hafta gününü bulan kısa bir kod yaz.",
    "Bir dizedeki ardışık boşlukları tek boşluğa düşüren tek satırlık kodu yaz.",
    "Bir Python sınıfının **`__slots__`** kullanımını gösteren minimalist bir sınıf tanımla.",

    # Ek Fonksiyonel Görevler (10)
    "Bir tarih/saat bilgisini UTC'ye çeviren ve formatlayan bir fonksiyon yaz.",
    "Bir şifreleme anahtarı (`key`) ve mesajı alarak **AES şifrelemesi** yapan temel bir kod yaz.",
    "Python'da çoklu kalıtım (multiple inheritance) kullanarak iki farklı arayüzü (interface) miras alan bir sınıf yaz.",
    "Bir `subprocess` çalıştıran ve hem stdout hem de stderr çıktılarını yakalayan bir fonksiyon yaz.",
    "Bir dizideki tüm tek sayıların karesini hesaplayan bir **generator** fonksiyonu yaz.",
    "Bir sınıftaki **`@property`** decorator'ını kullanarak bir alanın nasıl kontrol edileceğini göster.",
    "Bir metin dosyasının son satırını **verimli** bir şekilde okuyan bir fonksiyon yaz (tüm dosyayı hafızaya yüklemeden).",
    "Python'da `collections.namedtuple` kullanarak basit bir veri yapısı oluştur.",
    "Bir listenin yinelenen (duplicate) elemanlarını **hızlı** bir şekilde bulan bir fonksiyon yaz.",
    "Basit bir **fabrika metodu (Factory Method)** desenini uygulayan bir sınıf örneği yaz."
]
# Gerçek projede PROMPT_POOL listenizi 2500 farklı ve çeşitli prompt ile doldurmalısınız!

# =========================================================================
# === 2. ANA İŞLEV ========================================================
# =========================================================================
def generate_ai_code(prompt: str, model_name: str) -> str | None:
    """OpenRouter üzerinden kod çıktısı alır."""
    client = openai.OpenAI(
        base_url="https://openrouter.ai/api/v1",
        api_key=OPENROUTER_API_KEY,
    )

    try:
        response = client.chat.completions.create(
            model=model_name,
            messages=[
                {"role": "user", "content": f"Write only {TARGET_LANGUAGE} code. Do not add explanations, comments outside code, or markdown backticks. Task: {prompt}"}
            ],
            # Temperature'ı biraz rastgele yaparak aynı prompt tekrar kullanılsa bile
            # farklı varyasyonlar üretmesini sağlıyoruz.
            temperature=random.uniform(0.6, 0.9) 
        )
        content = response.choices[0].message.content.strip()
        
        # Markdown temizliği
        content = content.replace("```python", "").replace("```", "").strip()
        
        return content
        
    except Exception as e:
        print(f" API Hatası ({model_name}): {e}")
        time.sleep(2) # Hata durumunda biraz bekle
        return None

def main():
    if "BURAYA" in OPENROUTER_API_KEY:
        print("LÜTFEN OpenRouter API Anahtarınızı giriniz!")
        return

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    # Mevcut dosya sayısını kontrol et (kaldığı yerden devam edebilmesi için)
    existing_files = [f for f in os.listdir(OUTPUT_DIR) if f.startswith("ai_") and f.endswith(".json")]
    collected_count = len(existing_files)
    file_index = collected_count + 1
    
    print(f"Havuzdaki Prompt Sayısı: {len(PROMPT_POOL)}")
    print(f"Mevcut Dosya: {collected_count}, Hedef: {MAX_AI_BLOCKS}")
    
    # --- KRİTİK DEĞİŞİKLİK: WHILE DÖNGÜSÜ ---
    # Prompt sayısı (800) hedef sayıdan (5000) az olsa bile
    # döngü başa sararak (modulo operatörü ile) devam eder.
    while collected_count < MAX_AI_BLOCKS:
        
        # Prompt'u sırayla seç (Liste bitince başa döner)
        prompt_index = collected_count % len(PROMPT_POOL)
        prompt = PROMPT_POOL[prompt_index]
        
        # Modeli sırayla seç
        model_name = AI_MODELS[collected_count % len(AI_MODELS)]
        
        print(f"\r[{collected_count + 1}/{MAX_AI_BLOCKS}] Model: {model_name.split('/')[1]}...", end="")

        code_block = generate_ai_code(prompt, model_name)
        
        # Validasyon: Kod en az 3 satır olmalı ve boş olmamalı
        if code_block and len(code_block.split('\n')) >= 3:
            
            # İSTEDİĞİNİZ JSON FORMATI
            data = {
                "code": code_block,
                "source": "test-data-ai",      # İsteğiniz üzerine sabitlendi
                "prompt": prompt,              # Gerçek prompt'u tutmak model eğitimi için DAHA İYİDİR.
                # Eğer illa "AI generated" yazsın istiyorsanız üstteki satırı silip şunu açın:
                # "prompt": "AI generated", 
                "license": "MIT",
                "language": TARGET_LANGUAGE
            }
            
            # Dosya isimlendirmesi: ai_1.json, ai_2.json ...
            filename = os.path.join(OUTPUT_DIR, f"ai_{file_index}.json")
            
            with open(filename, 'w', encoding='utf-8') as f:
                json.dump(data, f, indent=4, ensure_ascii=False)
            
            collected_count += 1
            file_index += 1
            
            # Hız limitine takılmamak için bekleme
            time.sleep(0.5)
        else:
            # Başarısız olursa (kod çok kısaysa) pas geç, döngü devam etsin
            print(" -> (Atlandı: Çıktı yetersiz)")
            time.sleep(0.2)

    print(f"\n\n--- AI KOD ÜRETİMİ TAMAMLANDI ---\nToplam {collected_count} dosya {OUTPUT_DIR} klasöründe.")

if __name__ == "__main__":
    main()